DROP TABLE IF EXISTS fleet;
DROP TABLE IF EXISTS ship;
DROP TABLE IF EXISTS sailor;
DROP TABLE IF EXISTS duty;
DROP TABLE IF EXISTS rank;

CREATE TABLE fleet (

  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL

);

CREATE TABLE ship (

  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  date_built VARCHAR(50) NOT NULL

);

CREATE TABLE sailor (

  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  birthdate DATE NOT NULL

);

CREATE TABLE duty (

  id INTEGER PRIMARY KEY,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  ship_id INTEGER NOT NULL REFERENCES ship(id) ON DELETE CASCADE,
  sailor_id INTEGER NOT NULL REFERENCES sailor(id) ON DELETE CASCADE,
  name VARCHAR(50) NOT NULL

);

CREATE TABLE rank (

  id INTEGER PRIMARY KEY,
  ship_id INTEGER NOT NULL REFERENCES ship(id) ON DELETE CASCADE,
  sailor_id INTEGER NOT NULL REFERENCES sailor(id) ON DELETE CASCADE,
  rank VARCHAR(50) NOT NULL

);